version: '3.8'
services:
  mysql:
    image: mysql:5.7
    container_name: java-final-mysql
    ports:
      - "33060:3306"
    volumes:
      - ./env/mysql/:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_ROOT_PASSWORD: root
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci